version: 2.0
jobs:
  build:
    docker:
      - image: emanguy/javafx-xvfb
    steps:
      - checkout
      - run: |
          xvfb-run ./gradlew test
          mkdir -p test-results/JUnit
          mv build/test-results/test/*.xml test-results/JUnit/
      - store_test_results:
          path: test-results

